### ISSUE TITLE
4x size for the preview

### ISSUE THREAD

**Issue by taylorling** [marcisme/sketch-preview#18]
Now I started using Nexus 6 as my design device and the max preview output size cannot send the full screen artboard to the phone. The artboard is sized at 360x640, so after 4X it is 1440x2560, which is the resolution of Nexus 6.

**Comment by marcisme** [comment]
So does 4x correspond to xxxhdpi? I'm not overly familiar with Android design, but assuming this adds on to the previously available densities, I think it makes sense to just add 4x to the current list of sizes.

Once 4x is an option, is there still a need for an arbitrary size?

**Comment by taylorling** [comment]
Yeap, definitely, it's for xxxhdpi. 

No really for my case - I think 4x is good for now.

**Comment by marcisme** [comment]
This should work on the [4x branch](https://github.com/marcisme/sketch-preview/tree/4x). Try it out, and let me know how it works for you.

**Comment by taylorling** [comment]
Yeap, it is working perfectly for me, thanks! Should be fine to merge to the main ;)

**Comment by marcisme** [comment]
Thanks for testing. This is merged and available in *v0.7.0*.
