### ISSUE TITLE
Broken in Sketch Version 3.3 (11624)?

### ISSUE THREAD

**Issue by allmakebelieve** [marcisme/sketch-preview#19]
Hi,

This no longer seems to be working in the latest beta of Sketch 3.3. I'm unable to launch Preview Setup, and previewing no longer seems to send anything to Skala.

Tried re-installing and still no luck. Are you experiencing the same issue?

Thanks!

Pierre

**Comment by marcisme** [comment]
Thanks for reporting this.

It looks like the import directive has changed from `#import` to `@import`. I've fixed this in the [beta](https://github.com/marcisme/sketch-preview/tree/beta) branch, but I don't think there's any way to make this backwards compatible with 3.2.

Give the beta branch a try, and let me know if that doesn't work for you.

**Comment by allmakebelieve** [comment]
Awesome! Thanks so much, that did the trick :)


On February 22, 2015 at 1:09:26 PM, Marc Schwieterman (notifications@github.com) wrote:

Thanks for reporting this.

It looks like the import directive has changed from #import to @import. I've fixed this in the beta branch, but I don't think there's any way to make this backwards compatible with 3.2.

Give the beta branch a try, and let me know if that doesn't work for you.

**Comment by marcisme** [comment]
It looks like this was made backwards compatible in later builds of 3.3, so this change is no longer required.
