### ISSUE TITLE
@2x Preview

### ISSUE THREAD

**Issue by jdsimcoe** [marcisme/sketch-preview#23]
I work in 1x in my artboards and set them to export 2x. How do I get this plugin to allow 2x exporting to Skala Preview?

**Comment by marcisme** [comment]
If you type *⌘⌥P* or select *Plugins -> Preview Setup...* you can choose either *Scale for iPhone* or *Scale to explicit size* as appropriate.

If that doesn't work, try checking the *Enable debug logging* option and report back with the log output.

**Comment by jdsimcoe** [comment]
Beautiful thanks @marcisme!

**Comment by marcisme** [comment]
You're welcome. :)
