### ISSUE TITLE
Issue on Sketch 3.4.2

### ISSUE THREAD

**Issue by GabrielAraujo** [marcisme/sketch-preview#28]
Is it working for sketch 3.4.2?

I'm trying to preview a artboard but it is failing.

**Comment by marcisme** [comment]
There's at least one bug with the wrong document being used still in 3.4.2. The 3.4.3 beta is supposed to fix the known issue, so you might want to try that.

If the beta doesn't work, post back with some more information about what specifically is happening. Checking the debug option and including logs from the console would also be helpful.

**Comment by GabrielAraujo** [comment]
Hey, I was having a problem with the Skala Preview app.. It was my bad.. Sorry ;(
