### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by cmcky** [marcisme/sketch-preview#29]
Sketch 3.4.4 & Scala View 2.0

Neither is detecting the other. thing helpful in the console. Is anyone else able to reproduce this?

**Comment by marcisme** [comment]
I just tried with 3.4.4, and it's working for me.

Is there any output at all in the console if you check the debug option? If not, I'd double check that there's only one version of the plugin in the plugin directory, and make sure it's showing up and enabled under `Preferences -> Plugins`.

**Comment by cmcky** [comment]
Thanks. All fixed. Silly me, didn't reinstall Skala for mac.

**Comment by marcisme** [comment]
You're not the first person to have that experience. ;) Glad it's working now.
