### ISSUE TITLE
command+P can't send artboard to android phone

### ISSUE THREAD

**Issue by wymanLeung** [marcisme/sketch-preview#35]
Press command+P can't send artboard to android phone , devices is connected . but command+c copy artboard is working .
sketch  v3.5.2
skala preview v 0.8.0
skala for mac v2.0(207)
skala for android v2.0.3

**Comment by marcisme** [comment]
I believe the max image size that Skala Preview can display on some android devices is limited by the size of the texture buffers in their GPUs. What I suspect may be happening is that the copy method is using a smaller scaling factor than the (cmd-p) preview command.

What scaling factor is set in the (cmd-opt-p) preview settings?

If it's > 1x, does a lower setting work?

**Comment by wymanLeung** [comment]
Sorry , my english is poor , but i can understood you comment . I think i have found the cause , if I running skala preview for mac first , then press cmd+p will not working , it will be open a skala preview for new .  But if this not the case (don't running skala preview for mac first),that will be work . Now everything is ok , thanks!
