### ISSUE TITLE
Conflicting Keyboard Commands

### ISSUE THREAD

**Issue by diegozaks** [marcisme/sketch-preview#36]
Hi, is there a way to change the custom keyboard command to run this plugin?
The very popular Invision/Craft plugin also uses "Cmd + P".

**Comment by marcisme** [comment]
You can go to `System Preferences` -> `Keyboard` -> `Shortcuts` -> `App Shortcuts`, then click the little `+` icon there, select `Sketch` in the `Application` dropdown menu, enter `Preview` in the `Menu Title` field and assign your desired shortcut. Once you've done that, the shortcut displayed in the `Plugins` menu in Sketch itself should change to whatever you specified.

**Comment by diegozaks** [comment]
perfect, thank you

**Comment by marcisme** [comment]
You're welcome.  Happy Sketching. :)
