### ISSUE TITLE
Crashing with Auto Preview

### ISSUE THREAD

**Issue by marcisme** [marcisme/sketch-preview#37]
Kévin on Twitter reported:

> Awesome plugin but since live updates Sketch crash a lot… :(

Can you answer any of the questions below? This will help me reproduce the problem.

* What version of Sketch? (*Sketch* -> *About Sketch*)
* What version of OS X? (** -> *About this Mac*)
* Does the problem only happen while *Auto Preview* is enabled?
* How big is the Sketch document?
* How many Artboards?
* Roughly how many layers?
* Which version of Sketch was used to create the document?
* Does the plugin cause a crash when doing anything specific? Selecting different layers? Changing the document in some way?
* Is there any output in Console.app when the crash occurs? (*Applications* -> *Utilities* -> *Console*)
* Is there a crash report with a stack trace when Sketch is restarted?
* Can you reproduce the crash, or does it seem to happen at random?
* Does it only happen after Sketch has been open for a while, or does it sometimes happen right away?
* Does the problem happen with new documents or only this specific one?
* Anything else you may have noticed when the crash occurs?

**Comment by marcisme** [comment]
I spent some time trying to reproduce a crash tonight with a Sketch 3.8.3 document. I added tons of layers and artboards, but I was unable to get it to crash.

**Comment by humanator** [comment]
Sketch: Version 3.8.3 (29802)
Mac OS X: 10.11.5 (15F34)
Crash happened when enabled, but not previewing
Two documents:
9.8mb & 7.6mb
27 & 22 Artboards
3 pages each (one for design, one for material design sticker sheet and one for symbols
29 symbols & 29 symbols (including nested symbols)
No. layers per dartboard is less than 10, but each dartboard has multiple symbols
The crash seems to occur when saving, it will beachball for a while and then crash, no data lose appears to have happened so the crash is probably happening after the save completes.
I have crash logs for each crash in the console (I assume you want to see them?)

**Comment by marcisme** [comment]
@humanator Thanks for the information. This will give me some more test cases to try.

The crash logs would be great too. You can drop them at https://www.dropbox.com/request/6oBfTbiq0OweyS9K8I8c or email them to preview at marcis.me.

**Comment by SUPK187** [comment]
Hello @marcisme

I tried the plugin today and unfortunately sketch crash again.

I may have found a partial solution ! :)

After the crash of sketch I consulted the console app and I noticed that the script below was looping while sketch was off:

• 24/06/2016 12:34:11,574 Preview (Sketch Plugin)[1004]: DEBUG: config loaded from: file:///Users/SUPK187/Library/Caches/com.marcisme.sketch-preview/config.plist

• 24/06/2016 12:34:11,581 Preview (Sketch Plugin)[1004]: DEBUG: writing preview image to: /Users/SUPK187/Library/Caches/com.marcisme.sketch-preview/preview.png

• Version 3.8.3 (29802)
• OS X Yosemite, version 10.10.5

Thank you for your help

**Comment by marcisme** [comment]
@humanator I still can't reproduce the crash, but I'll keep trying. For now I've removed document saving from the events that will trigger a preview, and I've released v0.10.1. Let me know if this fixes the issue for you.

@SUPK187 Thanks for the information and the crash log. There were nearly 2000 threads, most of which seemed to be running sketch plugin code, so I must be hitting some kind of leak. The change I mentioned about may help, but I don't know if these are the same issue yet.

**Comment by marcisme** [comment]
@humanator @SUPK187 I think I've fixed the thread/memory leak issues, and I've released `v0.10.2`. If you have a chance to try it out, please let me know if it fixes the problem.

**Comment by SUPK187** [comment]
@marcisme Great news! I'll test tomorrow and I come to you.

**Comment by SUPK187** [comment]
@marcisme I think you've solved the problem. Zero crash today. 👍

**Comment by marcisme** [comment]
@SUPK187 Awesome! Thanks for your help and feedback.

**Comment by marcisme** [comment]
@humanator Thanks for the crash reports. Have you tried the latest version? (`v0.10.2`)

**Comment by marcisme** [comment]
Thanks for your help with this issue.
