### ISSUE TITLE
Live update fails with older version of Sketch (3.3.3)

### ISSUE THREAD

**Issue by ChristopherAlan** [marcisme/sketch-preview#38]
This probably isn't a surprise but thought I would post: I have to run an older version of Sketch for work (long story) so just thought I would test the live feature. It doesn't update automatically but the rest of the plugin still works great.

**Comment by marcisme** [comment]
Thanks for the report. I believe the actions/event feature was added in 3.8, so I unfortunately can't do anything to make the feature work in older versions. Please let me know if something else breaks though, as I'm trying to keep the plugin backwards compatible where possible.
