### ISSUE TITLE
incompatible with Sketch v41 (beta)

### ISSUE THREAD

**Issue by RaphyRaph** [marcisme/sketch-preview#39]

**Comment by marcisme** [comment]
Thanks for reporting this issue.

Does this [branch](https://github.com/marcisme/sketch-preview/tree/beta41) for the v41 beta work for you?

**Comment by RaphyRaph** [comment]
preview works!
auto-preview does not, however.

**Comment by marcisme** [comment]
So far in my testing auto-preview is working with this change.

Can you turn on the debug logging option and post the output from `Console.app` here?

**Comment by evandiamond** [comment]
Hi, when do we think a fix will be pushed? Thank you for all your help on this great plugin!

**Comment by marcisme** [comment]
@evandiamond I released a new version over the weekend that "works on my machine".

* Is preview working for you, but not auto-preview?
* Does it work for some documents but not others? What's different about them?
* Can you enable the debug logging option and post the output from `Console.app` here?

I'll keep testing as I think of new things to try, but I need to be able to reproduce the failure before I can fix it, and it's unfortunately (ha) working for me.

**Comment by evandiamond** [comment]
@marcisme 

Can you give me some details on how I would do 'Console.app'.

I installed the new version and cannot get it to run on any artboard in version 41

**Comment by marcisme** [comment]
You can run it from spotlight (⌘+space) by typing "console" or directly from `Applications` -> `Utilities`. There's a [post](http://developer.sketchapp.com/examples/code/debugging/) on the Sketch site that shows how to create a filter for just the log messages from Sketch, although you don't necessarily have to do that.

Usually when a plugin fail, Sketch will log some kind of error message that should help figure out where it's failing. The debug logging option will add some more detail to further help figure out where in the export process things are going wrong.

Thanks for your help figuring this out.

**Comment by evandiamond** [comment]
​Does this help?

 «Plugin Output»
TypeError: MSExportRequest.requestWithRect_scale is not a function. (In
'MSExportRequest.requestWithRect_scale(rect,2)',
'MSExportRequest.requestWithRect_scale' is undefined)
line: 10
sourceURL: /Users/evan/Library/Application
Support/com.bohemiancoding.sketch3/Plugins/Preview in
browser.sketchplugin/Contents/Sketch/script.cocoascript
column: 62
stack: onRun@/Users/evan/Library/Application
Support/com.bohemiancoding.sketch3/Plugins/Preview in
browser.sketchplugin/Contents/Sketch/script.cocoascript:10:62
 «Plugin Output»
TypeError: MSExportRequest.requestWithRect_scale is not a function. (In
'MSExportRequest.requestWithRect_scale(rect,2)',
'MSExportRequest.requestWithRect_scale' is undefined)
line: 10
sourceURL: /Users/evan/Library/Application
Support/com.bohemiancoding.sketch3/Plugins/Preview in
browser.sketchplugin/Contents/Sketch/script.cocoascript
column: 62
stack: onRun@/Users/evan/Library/Application
Support/com.bohemiancoding.sketch3/Plugins/Preview in
browser.sketchplugin/Contents/Sketch/script.cocoascript:10:62
 «Plugin Output»
TypeError: MSExportRequest.requestWithRect_scale is not a function. (In
'MSExportRequest.requestWithRect_scale(rect,2)',
'MSExportRequest.requestWithRect_scale' is undefined)
line: 10
sourceURL: /Users/evan/Library/Application
Support/com.bohemiancoding.sketch3/Plugins/Preview in
browser.sketchplugin/Contents/Sketch/script.cocoascript
column: 62
stack: onRun@/Users/evan/Library/Application
Support/com.bohemiancoding.sketch3/Plugins/Preview in
browser.sketchplugin/Contents/Sketch/script.cocoascript:10:62
 «Plugin Output»
TypeError: MSExportRequest.requestWithRect_scale is not a function. (In
'MSExportRequest.requestWithRect_scale(rect,2)',
'MSExportRequest.requestWithRect_scale' is undefined)
line: 10
sourceURL: /Users/evan/Library/Application
Support/com.bohemiancoding.sketch3/Plugins/Preview in
browser.sketchplugin/Contents/Sketch/script.cocoascript
column: 62
stack: onRun@/Users/evan/Library/Application
Support/com.bohemiancoding.sketch3/Plugins/Preview in
browser.sketchplugin/Contents/Sketch/script.cocoascript:10:62
 «Plugin Output»​




On Wed, Nov 9, 2016 at 11:12 AM, Marc Schwieterman <notifications@github.com
> wrote:

> console





*Evan*

**Comment by RaphyRaph** [comment]
works fine for me now on v41. Thanks!

**Comment by marcisme** [comment]
@RaphyRaph Awesome! Thanks for the update.

@evandiamond That is helpful. The error in that message looks like it's still using the old version for some reason. I'd try restarting sketch. If that doesn't work, you can delete the plugin from  `Plugins` -> `Manage Plugins...` and reinstall.

**Comment by marcisme** [comment]
This should work now. Let me know that's not the case, and we can investigate further.
