### ISSUE TITLE
android

### ISSUE THREAD

**Issue by lubustaman** [marcisme/sketch-preview#41]
skala is not working in android

**Comment by marcisme** [comment]
Does the image show up in the `Skala Preview` application on your mac?

If that works, there are some limitations with some android devices as mentioned in #32, or you may also be running into the issue from #34.

Otherwise if you could check the *Debug Logging* option in the plugin setup, and post the output from `Console.app` here when using the plugin, along with some more detail, I'll try to figure out what's going on.

**Comment by rodmaia2099** [comment]
I have a similar problem as @lubustaman and no, the image doesn't show on Skala Preview :(

Here's the log:

`09/01/17 17:05:43,847 Preview (Sketch Plugin)[694]: DEBUG: config loaded from: file:///Users/rodmaia/Library/Caches/com.marcisme.sketch-preview/config.plist
09/01/17 17:05:43,848 Preview (Sketch Plugin)[694]: DEBUG: config: {
    debug = 1;
    previewSizeIndex = 3;
    scalingStrategyId = 1;
}
09/01/17 17:05:43,848 Preview (Sketch Plugin)[694]: DEBUG: Searching for named preview slice: Preview
09/01/17 17:05:43,850 Preview (Sketch Plugin)[694]: DEBUG: No named preview slice found
09/01/17 17:05:43,850 Preview (Sketch Plugin)[694]: DEBUG: Searching for selected Artboard
09/01/17 17:05:43,850 Preview (Sketch Plugin)[694]: DEBUG: Found selected Artboard: Rename alt A
09/01/17 17:05:43,851 Preview (Sketch Plugin)[694]: DEBUG: writing preview image to: /Users/rodmaia/Library/Caches/com.marcisme.sketch-preview/preview.png
09/01/17 17:05:43,852 Preview (Sketch Plugin)[694]: DEBUG: searching for scalingStrategyId: 1
09/01/17 17:05:43,852 Preview (Sketch Plugin)[694]: DEBUG: found strategy: Scale to explicit size
09/01/17 17:05:43,852 Preview (Sketch Plugin)[694]: DEBUG: preview scale factor: 2
09/01/17 17:05:43,854 Sketch[694]: Exception: TypeError: MSExportRequest.requestWithRect_scale_ is not a function. (In 'MSExportRequest.requestWithRect_scale_( rect  ,size)', 'MSExportRequest.requestWithRect_scale_' is undefined)
09/01/17 17:05:43,854 Preview (Sketch Plugin)[694]: TypeError: MSExportRequest.requestWithRect_scale_ is not a function. (In 'MSExportRequest.requestWithRect_scale_( rect  ,size)', 'MSExportRequest.requestWithRect_scale_' is undefined)
line: 404
sourceURL: /Users/rodmaia/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Sketch Preview/SketchPreview.sketchplugin/Contents/Sketch/Preview.sketchscript
column: 48
`

**Comment by lubustaman** [comment]
well, after a few dead screens, it worked.

**Comment by lubustaman** [comment]
Try reinstalling both skala view, and preview

**Comment by rodmaia2099** [comment]
It worked! Thanks!
