### ISSUE TITLE
The plugin no longer recognizes Skala Preview

### ISSUE THREAD

**Issue by zhangchong0127** [marcisme/sketch-preview#43]
Have Skala Preview installed but the plugin can no longer recognize it. Error message: "Failed to open preview file; Make sure 'Skala Preview' is installed.

OS: High Sierra 10.13.2
Sketch: 48.2
Skala Preview: 2.0 (207)

Appreciate the help!

**Comment by marcisme** [comment]
I just tried to reproduce this, and it "works on my machine" with the same versions of software that you're using.

The plugin uses [`openFile(_:withApplication:andDeactivate:)`](https://developer.apple.com/documentation/appkit/nsworkspace/1530182-openfile) to open the preview image it exports, which you should be able to simulate from the terminal using the following.

```
open -a 'Skala Preview'
```

If running that command launches Skala Preview, then the plugin should work.

Did you happen to rename Skala Preview to something else? If so, and you want to keep it named that way, you can update [this line](https://github.com/marcisme/sketch-preview/blob/master/SketchPreview.sketchplugin/Contents/Sketch/Preview.sketchscript#L28) in the plugin bundle with the new name you're using.

Other than that, the only other thing that I can think of is that your Launch Services database may be corrupted. You can reset that, but I'm hesitant to recommend trying that unless it's the most likely issue, and you're familiar with that procedure.

**Comment by marcisme** [comment]
I'm going to assume this is working now. Let me know if that's not the case.
