### ISSUE TITLE
Keyboard shortcut no longer working

### ISSUE THREAD

**Issue by adbl** [marcisme/sketch-preview#45]
Thanks for a great plugin! 

In Sketch 49 they added Prototyping where "Preview Prototype..." has stolen the keyboard shortcut for Sketch Preview. I use this like every other minute 😆

**Comment by marcisme** [comment]
Thank you!

I'll think about a new shortcut. In the interim, you may be able to use the "Auto Preview" feature, or you can also bind a different key to the menu command as discussed in #36.

**Comment by adbl** [comment]
Cool!

**Comment by marcisme** [comment]
The `Preview` command is now `⌘⇧P`. Thanks for reporting this!
