### ISSUE TITLE
Request/Interest Alternative to Skala

### ISSUE THREAD

**Issue by p0wl** [marcisme/sketch-preview#48]
Hey, first of all thanks for your awesome plugin.

I got it working, but Skala Preview was not really reliable or slow and I think it's odd to install a separate App just for a preview.

I was wondering what you think about getting rid of it? I think a webpage that just displays the image in fullscreen is more than enough for most use cases. It would also allow to expand the functionality much further if need.

After a few hours I got a quick spike working:
* starting an http-server from within the sketch plugin that basically serves the cache-directory
* writing the latest preview filename to a "latest" file in the cache directory
* creating an index.html which includes very basic functionality like a fullscreen button (using https://github.com/sindresorhus/screenfull.js)
* a script embedded in index.html which fetches the content of the "latest" file periodically and renders the content in an image tag

you can see the changes I made for the spike here: https://github.com/marcisme/sketch-preview/compare/master...p0wl:http-server?expand=1

notes: I had to switch back to png because most browsers don't render .tiff. Also: right now index.html has to be copied to the cache directory by hand, since I had no idea how/where to do it in the plugin.

The proposed solution could be an alternative or a replacement to Skala.

I'm still not quite sure if this is a good approach (especially "embedding" the webserver within the plugin), so I thought I'd ask if you would be willing to accept contributions in that direction.

Let me hear what you think!

Spike (bad quality because of gif):
![sketch_mirror](https://user-images.githubusercontent.com/596578/40257300-04070486-5aee-11e8-8d00-f720b8dd2fea.gif)

**Comment by marcisme** [comment]
@p0wl Thank you for taking the time to put together this spike.

I have a few concerns with this approach.

* Running an HTTP server process is significantly more complicated than the current approach. That brings with it the stability and resource usage of an unfamiliar background process, as well as issues like port conflicts or local firewall interference
* This seems like it would let you preview locally, but tools like Skala Preview let you preview on device
* Skala View has modes for various visual accessibility testing, such as color blindness
* Skala Preview also supports Photoshop, so it's possible users working in both Photoshop and Sketch value having the same on-device experience for both document types

Based on the complexity and feature differences above, I don't think this approach would make for a good replacement, and I don't have the time to maintain and support the changes that would be needed to make it an alternative. I think this is an interesting idea that would probably be best served by a separate plugin. You're certainly welcome to fork as a starting point.

You may want to check out some of the following, similar tools.

* https://xscopeapp.com/guide#mirror
* http://mirapp.io
* https://www.sketchapp.com/docs/mirror/

**Comment by p0wl** [comment]
Hey @marcisme thanks for your fast reply.

I agree with all your concerns (did not know Skala View has accessibility testing modes, that's awesome!), nonetheless I see benefits in having a preview that works in a browser as it is much easier to show to different persons without having to install an app on their device.
None of the solutions I found (or the ones you mentioned) is able to do that.

I think of providing a qr code or something in order to display the preview on mobile devices. Local preview (as in my gif) is of course not really helpful.

I'll take your plugin as a starting point. Thanks for the offer!

**Comment by marcisme** [comment]
@p0wl I can see how that would be useful.

You may also want to check out [InVision](https://www.invisionapp.com) and [Sketch Cloud](https://www.sketchapp.com/docs/sketch-cloud/). I've had mostly good experiences with InVision, but I haven't used Sketch Cloud.

Good luck and have fun with it!
