### ISSUE TITLE
How do I change it?

### ISSUE THREAD

**Issue by 1150066474** [marcisme/sketch-preview#50]
Error message

failed to open preview file ;make sure skala preview is installed

**Comment by 1150066474** [comment]
Have previewed and updated, or can't see preview

**Comment by marcisme** [comment]
Does `Skala Preview` work by itself? Usually if you can get that working, the plugin will work too.

Once you've gotten that far, you can turn on the [debug logging](https://github.com/marcisme/sketch-preview#troubleshooting) to get more information.
